services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/windows-dockur/windows.7z/windows%2Fdata.img"
      DISPLAY: "vnc"
      CPU_CORES: "4"
      RAM_SIZE: "6G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 5900:5900/tcp
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
