services:
  windows:
    image: dockurr/windows
    deploy:
      resources:
        limits:
          memory: 16g
    container_name: windows
    environment:
      VERSION: "11"
      DISPLAY: "vnc"
      CPU_CORES: "4"
      RAM_SIZE: "12G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 5900:5900/tcp
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
