name: Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Setup NGROK
        run: |
             wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
             sudo tar -xvzf ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
             cd /home/runner/work/windows-qemu/windows-qemu
             mkdir -p ~/.config/ngrok
             cp ngrok.yml ~/.config/ngrok/ngrok.yml
             ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
             cat ~/.config/ngrok/ngrok.yml
             
      - name: Start Windows
        run: |
             cd /home/runner/work/windows-qemu/windows-qemu
             docker compose up -d
             sudo apt install nmap && nmap localhost
             ngrok start --all --log=stdout
