name: Windows

on: 
  workflow_dispatch:
permissions:
  contents: write  # Required for GITHUB_TOKEN to push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Setup NGROK
        run: |
             wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
             wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.49.0/fastfetch-linux-amd64.tar.gz
             sudo tar -xvzf ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
             sudo tar -xvzf fastfetch-linux-amd64.tar.gz -C /usr/local/bin fastfetch-linux-amd64/usr/bin/fastfetch --strip-components=3
             cd /home/runner/work/windows-qemu/windows-qemu
             mkdir -p ~/.config/ngrok
             cp ngrok.yml ~/.config/ngrok/ngrok.yml
             ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
             cat ~/.config/ngrok/ngrok.yml
             
      - name: Start Windows
        run: |
             mkdir -p windows storage
             sudo fastfetch -l none
             aria2c -s16 -x16 "https://archive.org/download/windows-docker/data.qcow2" --out windows/data.qcow2
             aria2c -s16 -x16 "https://download.microsoft.com/download/8/4/a/84a35bf1-dafe-4ae8-82af-ad2ae20b6b14/directx_Jun2010_redist.exe" --out storage/dxsetup.exe
             aria2c -s16 -x16 "https://archive.org/download/E3D_2.1.0-cr/Everything-3D-2.1.0_Crack.zip" --out e3d.zip
             unzip -d storage e3d.zip
             rm e3d.zip
             sudo echo "windows/data.qcow2" > windows/windows.boot
             docker run -d --rm --name windows \
             --memory=16g \
             -p 8006:8006 \
             -p 3389:3389/tcp \
             -p 3389:3389/udp \
             --device=/dev/kvm \
             --device=/dev/net/tun \
             --cap-add NET_ADMIN \
             -v "${PWD:-.}/windows:/storage" \
             -v $pwd/storage:/shared \
             --stop-timeout 120 \
             -e RAM_SIZE=14G \
             -e CPU_CORES=4 \
             dockurr/windows
             ngrok start --all --log=stdout
             
