name: Boot Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Setup Windows
        run: |
             mkdir windows && cd windows
             curl -H "Authorization: token ${{ secrets.WIN_PAT }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -L \
             https://api.github.com/repos/mjuned07/windows-qemu/contents/compose.yml?ref=master \
             -o compose.yml
             mkdir -p ~/.config/ngrok
             
      - name: Setup NGROK
        run: |
             curl -H "Authorization: token ${{ secrets.WIN_PAT }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -L \
             https://api.github.com/repos/mjuned07/windows-qemu/contents/ngrok.yml?ref=master \
             -o ngrok.yml
             curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
             | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
             && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
             | sudo tee /etc/apt/sources.list.d/ngrok.list \
             && sudo apt update \
             && sudo apt install ngrok
             ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
             
      - name: Start Windows
        run: |
             docker compose up -d && ngrok start --all --log=stdout
